[2024-01-31T15:44:41.786+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:44:41.027877+00:00 [queued]>
[2024-01-31T15:44:41.794+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:44:41.027877+00:00 [queued]>
[2024-01-31T15:44:41.795+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T15:44:41.808+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): process_vulnerability_data> on 2024-01-31 15:44:41.027877+00:00
[2024-01-31T15:44:41.813+0000] {standard_task_runner.py:60} INFO - Started process 17334 to run task
[2024-01-31T15:44:41.815+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'vulnerability_email_notification', 'process_vulnerability_data', 'manual__2024-01-31T15:44:41.027877+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/cvd_mail_and_reschedule.py', '--cfg-path', '/tmp/tmpimmk50k_']
[2024-01-31T15:44:41.816+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask process_vulnerability_data
[2024-01-31T15:44:41.852+0000] {task_command.py:423} INFO - Running <TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:44:41.027877+00:00 [running]> on host 8d8bbdf320cd
[2024-01-31T15:44:41.922+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vulnerability_email_notification' AIRFLOW_CTX_TASK_ID='process_vulnerability_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T15:44:41.027877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T15:44:41.027877+00:00'
[2024-01-31T15:44:41.923+0000] {cvd_mail_and_reschedule.py:62} INFO - SMTP server connecting...
[2024-01-31T15:44:41.927+0000] {cvd_mail_and_reschedule.py:69} INFO - SMTP server connected successfully.
[2024-01-31T15:44:41.928+0000] {cvd_mail_and_reschedule.py:80} ERROR - Error loading JSON data: [Errno 2] No such file or directory: '/opt/***/data/enriched_nuclei_results/enriched_2024-01-30.json'
[2024-01-31T15:44:41.928+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-31T15:44:41.937+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=vulnerability_email_notification, task_id=process_vulnerability_data, execution_date=20240131T154441, start_date=20240131T154441, end_date=20240131T154441
[2024-01-31T15:44:41.987+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T15:44:42.003+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
