[2024-01-30T23:42:10.649+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:37:08.384011+00:00 [queued]>
[2024-01-30T23:42:10.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:37:08.384011+00:00 [queued]>
[2024-01-30T23:42:10.672+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-01-30T23:42:10.695+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): process_vulnerability_data> on 2024-01-30 23:37:08.384011+00:00
[2024-01-30T23:42:10.702+0000] {standard_task_runner.py:60} INFO - Started process 6954 to run task
[2024-01-30T23:42:10.706+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'vulnerability_email_notification', 'process_vulnerability_data', 'manual__2024-01-30T23:37:08.384011+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/cvd_mail_and_reschedule.py', '--cfg-path', '/tmp/tmp6r1qkzpr']
[2024-01-30T23:42:10.709+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask process_vulnerability_data
[2024-01-30T23:42:10.773+0000] {task_command.py:423} INFO - Running <TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:37:08.384011+00:00 [running]> on host 8d8bbdf320cd
[2024-01-30T23:42:10.882+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vulnerability_email_notification' AIRFLOW_CTX_TASK_ID='process_vulnerability_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T23:37:08.384011+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T23:37:08.384011+00:00'
[2024-01-30T23:43:06.269+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-30T23:43:06.279+0000] {process_utils.py:131} INFO - Sending 15 to group 6954. PIDs of all processes in the group: [6954]
[2024-01-30T23:43:06.280+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 6954
[2024-01-30T23:43:06.281+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-30T23:43:06.333+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=6954, status='terminated', exitcode=0, started='23:42:09') (6954) terminated with exit code 0
