[2024-01-30T23:47:28.372+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:47:27.482920+00:00 [queued]>
[2024-01-30T23:47:28.384+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:47:27.482920+00:00 [queued]>
[2024-01-30T23:47:28.385+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-30T23:47:28.407+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): process_vulnerability_data> on 2024-01-30 23:47:27.482920+00:00
[2024-01-30T23:47:28.414+0000] {standard_task_runner.py:60} INFO - Started process 7224 to run task
[2024-01-30T23:47:28.417+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'vulnerability_email_notification', 'process_vulnerability_data', 'manual__2024-01-30T23:47:27.482920+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/cvd_mail_and_reschedule.py', '--cfg-path', '/tmp/tmpgm99bjay']
[2024-01-30T23:47:28.419+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask process_vulnerability_data
[2024-01-30T23:47:28.479+0000] {task_command.py:423} INFO - Running <TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-30T23:47:27.482920+00:00 [running]> on host 8d8bbdf320cd
[2024-01-30T23:47:28.585+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vulnerability_email_notification' AIRFLOW_CTX_TASK_ID='process_vulnerability_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T23:47:27.482920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T23:47:27.482920+00:00'
[2024-01-30T23:49:14.309+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-30T23:49:14.312+0000] {process_utils.py:131} INFO - Sending 15 to group 7224. PIDs of all processes in the group: [7224]
[2024-01-30T23:49:14.313+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 7224
[2024-01-30T23:49:14.314+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-30T23:49:14.315+0000] {cvd_mail_and_reschedule.py:70} ERROR - Failed to connect to SMTP server: Task received SIGTERM signal
[2024-01-30T23:49:14.316+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T23:49:14.328+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=vulnerability_email_notification, task_id=process_vulnerability_data, execution_date=20240130T234727, start_date=20240130T234728, end_date=20240130T234914
[2024-01-30T23:49:14.367+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=7224, status='terminated', exitcode=0, started='23:47:27') (7224) terminated with exit code 0
