[2024-01-30T18:39:07.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-30T18:38:16.938700+00:00 [queued]>
[2024-01-30T18:39:07.707+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-30T18:38:16.938700+00:00 [queued]>
[2024-01-30T18:39:07.708+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-30T18:39:07.719+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): enrich_nuclei_data_task> on 2024-01-30 18:38:16.938700+00:00
[2024-01-30T18:39:07.724+0000] {standard_task_runner.py:60} INFO - Started process 1011 to run task
[2024-01-30T18:39:07.725+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'enrich_nuclei_data_task', 'manual__2024-01-30T18:38:16.938700+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/cvd_pipeline_1.py', '--cfg-path', '/tmp/tmpy08vagx_']
[2024-01-30T18:39:07.727+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask enrich_nuclei_data_task
[2024-01-30T18:39:07.762+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-30T18:38:16.938700+00:00 [running]> on host 8d8bbdf320cd
[2024-01-30T18:39:07.823+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='enrich_nuclei_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T18:38:16.938700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T18:38:16.938700+00:00'
[2024-01-30T18:39:10.502+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cvd_pipeline_1.py", line 148, in enrich_nuclei_data
    enriched_data = json.loads(stdout.decode('utf-8'))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-01-30T18:39:10.516+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cvd_automation_pipeline, task_id=enrich_nuclei_data_task, execution_date=20240130T183816, start_date=20240130T183907, end_date=20240130T183910
[2024-01-30T18:39:10.529+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task enrich_nuclei_data_task (Expecting value: line 1 column 1 (char 0); 1011)
[2024-01-30T18:39:10.552+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T18:39:10.567+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
